# Configuration file for Redis
# Read https://james.apache.org/server/config-redis.html for further details

# Redis connection
# Compulsory when a component relying on Redis is enabled
redisURL=redis://redis:6379
# Possible values: standalone, cluster, master-replica, sentinel. Defaults to standalone.
redis.topology=standalone
# Possible values: master, masterPreferred, replica, replicaPreferred, any. Defaults to master.
#redis.readFrom=master
#redis.ioThreads=16
#redis.workerThreads=32

# Redis mailbox caches
# Cache current quotas in Redis instead of storing them in Cassandra counters. Defaults to false.
redis.current.quota=false
# Cache mailbox counters (message count, unseen count) in Redis instead of reading them from Cassandra counters.
# Defaults to false.
# Advised: execute the counters listener synchronously by adding to jvm.properties:
#   james.eventbus.synchronous.listener.groups=RedisMailboxCountersListenerGroup
redis.mailbox.counters=false
# Duration during which cached values are kept. Defaults to 1 day.
#redis.cache.ttl=1d
# Random duration, between zero and this value, added to the TTL of each cached value. Defaults to 0 (no jitter).
#redis.cache.ttl.jitter=2h
